### ISSUE TITLE
How to generate the gif?

### ISSUE THREAD

**Issue by fangbohui** [kodai100/MPMSnowSimulation2D#1]
Hi! Very glad to see your project. Would you please teach me how to get the gif from the GL codes, like those in your ‘Thumbnails’?

**Comment by kodai100** [comment]
Hi fangbohui !
My thumbnails were captured as sequential .png files with FreeImage library.
[http://freeimage.sourceforge.net/](http://freeimage.sourceforge.net/)

After capturing, we have to bring these to Photoshop or something to generate gif animation.

**Comment by fangbohui** [comment]
Cool!
We eventually solved this problem by using some screen capture software on Ubuntu. Thanks for your help!
